login/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('user_edit/', views.user_edit, name='user_edit'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name="register"),
    path('teachers_register/', views.teachers_register, name="teachers_register"),
    path('logout/', views.logout, name='logout'),
    path('pswd_edit/', views.pswd_edit, name='pswd_edit'),

]

students/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="students_index"),
    path('kecheng/<int:id>', views.kecheng, name="students_kecheng"),
    path('kecheng_add/<int:id>', views.kecheng_add, name="students_kecheng_add"),
    path('cource_section_msg/<int:id>/<int:chapter_id>/<int:section_id>', views.cource_section_msg,
         name="cource_section_msg_students"),  # 课程评论留言
    path('exercises/<int:id>', views.exercises, name="students_exercises"),
    path('exercises_start/<int:id>/<int:exercises_id>', views.exercises_start, name="students_exercises_start"),
    path('calGrade/<int:id>/<int:exercises_id>', views.calGrade, name="students_calGrade"),
    path('showGrade/<int:id>/<int:exercises_id>', views.showGrade, name="students_showGrade"),

]

zaixianxuexixitong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('login.urls')),
                  path('teachers/', include('teachers.urls')),
                  path('students/', include('students.urls')),
                  path('myadmin/', include('myadmin.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  ## 没有这一句无法显示上传的图片

login/models.py
import datetime

from django.db import models


# students
class User(models.Model):
    name = models.CharField(verbose_name="用户名", max_length=32, default='')  #
    teacher_id = models.CharField(verbose_name="id", max_length=32, default='')  #
    teacher_name = models.CharField(verbose_name="姓名", max_length=32, default='')  #
    type = models.IntegerField(verbose_name="类型", default=1)  # 1普通用户|3教工号|4审核状态|5拒绝|6管理员|9禁用
    password = models.CharField(verbose_name="密码", max_length=32, default='')  # 管理员密码
    Class = models.CharField(verbose_name="班级", max_length=32, default='')
    academy = models.CharField(verbose_name="学院", max_length=32, default='')
    email = models.EmailField(verbose_name="邮箱", default='')
    phone = models.CharField(verbose_name="手机号", max_length=18, default='')
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    photo = models.ImageField(verbose_name="头像", upload_to='static/students/photo/', default='')
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'User'
        # 后台管理名
        verbose_name_plural = '用户列表'


# 课程名
class Course(models.Model):
    name = models.CharField(verbose_name="课程名", max_length=32, default='')  # 课程名
    type = models.IntegerField(verbose_name="课程类型", default=0)
    # 1.哲学|2.经济学|3.法学|4.教育学|5.文学
    user = models.ForeignKey(verbose_name="用户名", to="User", on_delete=models.CASCADE, default='')  # 创建用户名
    photo = models.FileField(verbose_name="资源存放名字", upload_to='Course/', default='')  # 课程图片
    introduction = models.TextField(verbose_name="课程简介")  # 课程简介
    audit = models.IntegerField(verbose_name="审核", default=1)  # 审核状态 1审核中|   2已审核|   3审核失败
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Course'
        # 后台管理名
        verbose_name_plural = '课程'


# 章
class Chapter(models.Model):
    name = models.ForeignKey(to="Course", on_delete=models.CASCADE, default='', null=True)  # 课程名
    chapter = models.CharField(verbose_name="章", max_length=210, default="")  # 章
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Chapter'
        # 后台管理名
        verbose_name_plural = '章'


# pdf,mp4资源
class Media(models.Model):
    type = models.IntegerField(verbose_name="类型", default=0)  # 1.pdf| 2.mp4   |3.word | 4.powerPoint
    media = models.FileField(verbose_name="资源存放地址", upload_to='static/Media/', default='')
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.media

    class Meta:
        # 数据库列表名
        db_table = 'Media'
        # 后台管理名
        verbose_name_plural = '资源存放地址'


# 节
class Section(models.Model):
    name = models.ForeignKey(to="Chapter", on_delete=models.CASCADE, default='')  # 章
    section = models.CharField(verbose_name="节", max_length=210, default="")
    media = models.ForeignKey(Media, on_delete=models.CASCADE)

    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Section'
        # 后台管理名
        verbose_name_plural = '节'


# message留言
class Message(models.Model):
    name = models.ForeignKey(to="Section", on_delete=models.CASCADE, default='')  # 节
    user = models.ForeignKey(to="User", on_delete=models.CASCADE, default='')
    message = models.CharField(verbose_name="留言", max_length=210, default='')  # 留言
    myTime = models.DateTimeField(verbose_name="参加时间", auto_now_add=True)

    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Message'
        # 后台管理名
        verbose_name_plural = '留言'


# 选课
class Course2(models.Model):
    students = models.ForeignKey(to="User", on_delete=models.CASCADE, default='')  # 用户名
    course = models.ForeignKey(to="Course", on_delete=models.CASCADE, default='')  # 课程名
    myTime = models.DateTimeField(verbose_name="参加时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.course

    class Meta:
        # 数据库列表名
        db_table = 'course2'
        # 后台管理名
        verbose_name_plural = '选课'


# 练习、习题
class Exercises(models.Model):
    exercises = models.CharField(verbose_name="练习题", max_length=210, default='')
    course = models.ForeignKey(verbose_name='课程', to="Course", on_delete=models.CASCADE, default='')
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.exercises

    class Meta:
        # 数据库列表名
        db_table = 'Exercises'
        # 后台管理名
        verbose_name_plural = '习题'


class Exercises2(models.Model):
    user = models.ForeignKey(verbose_name="用户", to="User", on_delete=models.CASCADE, default='')
    exercises = models.ForeignKey(verbose_name="联系题名", to="Exercises", on_delete=models.CASCADE, default='')
    course2 = models.ForeignKey(verbose_name='课程', to="Course2", on_delete=models.CASCADE, default='')
    grade = models.DecimalField(verbose_name="成绩", max_digits=5, decimal_places=2)
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        grade = str(self.grade)
        return grade

    class Meta:
        # 数据库列表名
        db_table = 'Exercises2'
        # 后台管理名
        verbose_name_plural = '习题成绩'


# 选择题
class Answer(models.Model):
    exercises = models.ForeignKey(to="Exercises", on_delete=models.CASCADE, default='')
    title = models.TextField(verbose_name="问题", max_length=210, default='')
    answerA = models.CharField(verbose_name="答案A", max_length=110, default='')
    answerB = models.CharField(verbose_name="答案B", max_length=110, default='')
    answerC = models.CharField(verbose_name="答案C", max_length=110, default='')
    answerD = models.CharField(verbose_name="答案D", max_length=110, default='')
    correctAnswer = models.IntegerField(verbose_name="正确答案", default=0)  # A B C D ___ 1 2 3 4
    number = models.IntegerField(verbose_name="分值", default=2)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.title

    class Meta:
        # 数据库列表名
        db_table = 'Answer'
        # 后台管理名
        verbose_name_plural = '选择题'


class Answer2(models.Model):
    user = models.ForeignKey(verbose_name="学生", to="User", on_delete=models.CASCADE, default="")
    exercises = models.ForeignKey(verbose_name="练习题", to="Exercises", on_delete=models.CASCADE, default="")
    answer = models.ForeignKey(verbose_name="问题", to="Answer", on_delete=models.CASCADE, default='')
    stuAnswer = models.IntegerField(verbose_name="学生答案", default=0)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        answer = str(self.stuAnswer)
        return answer

    class Meta:
        # 数据库列表名
        db_table = 'Answer2'
        # 后台管理名
        verbose_name_plural = '学生答案'


class Teachers(models.Model):
    nickName = models.CharField(verbose_name="用户名", max_length=110, default='')
    name = models.CharField(verbose_name="姓名", max_length=110, default='')
    type = models.IntegerField(verbose_name="类型", default=1)  # 1普通用户|6管理员|9禁用
    password = models.CharField(verbose_name="密码", max_length=32, default='')  # 管理员密码
    email = models.EmailField(verbose_name="邮箱", default='')
    phone = models.CharField(verbose_name="手机号", max_length=11, default='')
    photo = models.ImageField(verbose_name="头像", upload_to='teachers/photo/', default='')
    myTime = models.DateTimeField(verbose_name="参加时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)


class MyTime(models.Model):
    myTime = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=110, default='')

students/models.py
from django.db import models

# Create your models here.

students/views.py
import os.path

from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from login.models import *


# Create your views here.
def index(request):
    name = request.session['name']
    a = User.objects.get(name=name)

    s = a.type

    course = Course2.objects.filter(students=a)
    return render(request, "studentes/stu_index.html", {"s": s, "course": course})


def kecheng(request, id):
    try:

        cource = Course.objects.get(id=id, is_active=True)

    except Exception as e:
        print("cource_edit:", e)
        msg = "没有此课程！"
        return render(request, 'teachers/prompt.html', {"msg": msg})

    chapter_id = request.GET.get('chapter')
    section_id = request.GET.get('section')

    chapter = Chapter.objects.filter(name__id=id, is_active=True)
    section = Section.objects.filter(name__name_id=id, is_active=True)

    if section_id:
        try:
            section_id = Section.objects.get(id=section_id, is_active=True)
            message = Message.objects.filter(name_id=section_id, is_active=True)
        except Exception as e:
            print("cource_edit section_id：", e)
            msg = "没有此课程！"
            # return render(request, 'teachers/prompt.html', {"msg": msg})

        return render(request, 'studentes/stu_class.html',
                      {"cource": cource, "chapter": chapter, "section": section, "id": id, "section_id": section_id,
                       "message": message})

    return render(request, 'studentes/stu_class.html',
                  {"cource": cource, "chapter": chapter, "section": section, "id": id})


def kecheng_add(request, id):
    try:
        cource = Course.objects.get(id=id)
    except Exception as e:
        print("student_kecheng_add:", e)
        msg = "没有此课程！"
        return render(request, 'studentes/prompt.html', {"msg": msg})
    if request.method == 'GET':
        name=request.session.get('name')
        try:

            ss = Course2.objects.filter(course_id=cource,students_id=User.objects.get(name=name),is_active=True)
        except Exception as e:
            print("students_kecheng_add",e)
        if ss:
            return HttpResponseRedirect('/students/kecheng/' + str(id))
        return render(request, 'studentes/cource_add.html', {"cource": cource})
    if request.method == 'POST':
        user = request.session.get('name')
        try:
            user = User.objects.get(name=user)
            ss = Course2.objects.filter(students=user, course=cource)
        except Exception as e:
            print("students_kecheng_add:", e)
        if ss:
            msg = "你已经参加了这门课程！"
            return render(request, 'studentes/prompt.html', {"msg": msg})

        course2 = Course2.objects.create(course=cource, students=user)
        if course2:
            return HttpResponseRedirect('/students/kecheng/' + str(id))
        else:
            msg = "添加失败！"
            return render(request, 'studentes/prompt.html', {"msg": msg})


def exercises(request, id):
    try:
        user = request.session.get('name')
        user = User.objects.get(name=user)
        cource = Course.objects.get(id=id)
        exercise = Exercises.objects.filter(is_active=True, course_id=id)
        exercise2 = Exercises2.objects.filter(is_active=True, course2__course_id=id, user=user)
    except Exception as e:
        print("student_exercises:", e)
        msg = "没有此课程！"
        return render(request, 'studentes/prompt.html', {"msg": msg})
    if request.method == 'GET':
        a = []
        # try:
        #     for i in exercise:
        #         b = []
        #         b.append(i)
        #         exe = Exercises2.objects.get(is_active=True, course2__course_id=id, user=user, exercises_id=i.id)
        #         b.append(exe)
        #         a.append(b)
        # except Exception as e:
        #     print("stduents_exercises:", e)

        return render(request, 'studentes/exercises_index.html', {"exercise": exercise, "exercise2": exercise2, "a": a})


def exercises_start(request, id, exercises_id):
    try:
        cource = Course.objects.get(is_active=True, id=id)
        exercise = Exercises.objects.get(is_active=True, id=exercises_id)
        answer = Answer.objects.filter(is_active=True, exercises_id=exercises_id)

    except Exception as e:
        print("student_exercises_start:", e)
        msg = "没有此练习题！"
        return render(request, 'studentes/prompt.html', {"msg": msg})
    if request.method == 'GET':
        return render(request, 'studentes/exercises_start.html',
                      {"exercise": exercise, "answer": answer, "course": cource})


def calGrade(request, id, exercises_id):
    user = request.session.get('name')
    user = User.objects.get(name=user)
    try:

        exercise = Exercises.objects.get(is_active=True, id=exercises_id)
        answer = Answer.objects.filter(is_active=True, exercises_id=exercises_id)
        cource2 = Course2.objects.get(course_id=id, students_id=user.id)

    except Exception as e:
        print("student_calgrade:", e)
        msg = "没有此练习题！"
        return render(request, 'studentes/prompt.html', {"msg": msg})

    if request.method == 'POST':
        myGrade = 0
        for i in answer:
            stu = request.POST[str(i.id)]
            # print(i.id, ":", exercise.id, ":", exercise.exercises, "+", stu)
            if i.correctAnswer == int(stu):
                myGrade = myGrade + 1
            ans = Answer2.objects.create(user=user, exercises=exercise, stuAnswer=stu,
                                         answer=Answer.objects.get(id=i.id))
        grade = myGrade / answer.count() * 100
        grade = round(grade, 2)
        ex = Exercises2.objects.create(user=user, exercises=exercise, course2=cource2, grade=grade, )

    return HttpResponseRedirect('/students/exercises/' + str(id))


# 留言
def cource_section_msg(request, id, chapter_id, section_id):
    try:
        cource = Course.objects.get(id=id)
        chapter = Chapter.objects.get(id=chapter_id)
    except Exception as e:
        print("cource_edit:", e)
        msg = "没有此课程或目录！"
    if request.method == 'GET':
        msg = request.GET.get('msg')
        user = request.session.get('name')
        ss = Message.objects.create(message=msg, user=User.objects.get(name=user),
                                    name=Section.objects.get(id=section_id))
        return HttpResponseRedirect('/students/kecheng/' + str(id))


def showGrade(request, id, exercises_id):
    user = request.session.get('name')
    user = User.objects.get(name=user)
    try:

        exercise = Exercises.objects.get(is_active=True, id=exercises_id)
        answer = Answer.objects.filter(is_active=True, exercises_id=exercises_id)
        cource2 = Course2.objects.get(course_id=id, students_id=user.id)
        ansewer2 = Answer2.objects.filter(user__name=user, exercises_id=exercises_id).values('stuAnswer')

    except Exception as e:
        print("student_calgrade:", e)
        msg = "没有此练习题！"
        return render(request, 'studentes/prompt.html', {"msg": msg})
    if request.method == 'GET':
        return render(request, 'studentes/showGrade.html',
                      {"exercise": exercise, "answer": answer, "course": cource2, "answer2": ansewer2})

students/templates/studentes/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    {% load static %}
    <!-- 必须的 meta 标签 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 的 CSS 文件 -->
    <link href="{% static  'bootsrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootsrap/js/bootstrap.bundle.min.js' %}"></script>

    <title>在线学习系统</title>
    <link rel="icon" href="{% static 'img/tubiao.jpg' %}" type="image/x-icon">


    <style type="text/css">

    </style>
    {% load static %}
</head>

{% load static %}
<body  background="{% static 'img/background.jpg' %}" style=" background-repeat:no-repeat ;background-size:100% 100%;
background-attachment: fixed;">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static 'img/tubiao.jpg' %}" style="margin-left: 20px" width="30" height="30">
            在线学习系统
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/students/">我的课程</a>
                </li>

            </ul>
            <ul class="navbar-nav  d-flex dropdown" style="--bs-scroll-height: 100px;margin-right: 30px">
                <a class="navbar-brand" href="/">

                </a>

                <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.session.name }}
{#                    <img src="{% static 'img/tubiao.jpg' %}" alt="" width="25" height="25">#}
                </a>

                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                    {% if request.session.type == 3 %}
                        <li><a class="dropdown-item" href="{% url 'teachers_index' %}">切换教师端</a></li>
                    {% elif request.session.type == 6 %}
                        <li><a class="dropdown-item" href="{% url 'myadmin_index' %}">切换后台管理端</a></li>
                    {% elif  request.session.type == 1 %}
                        <li><a class="dropdown-item" href="{% url 'teachers_register' %}">审核教师</a></li>
                    {% elif  request.session.type == 4 %}
                        <li><a class="dropdown-item" href="{% url 'teachers_register' %}">提交教师审核</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="#">编辑资料</a></li>
                    <li><a class="dropdown-item" href="{% url 'pswd_edit' %}">修改密码</a></li>
                    <li><a class="dropdown-item" href="/logout/">退出登录</a></li>
                </ul>
            </ul>

        </div>
    </div>
</nav>
{#coolpsase#}
<div class="col" style="opacity: 0.9;background-color: white;padding: 30px 30px 30px 30px;margin: 20px 20px 20px 20px;border-radius: 20px">
{% block students_index %}

{% endblock %}
</div>

</body>


</html>

students/templates/studentes/exercises_index.html
{% extends 'studentes/base.html' %}
{% block students_index %}
    <div class="container">
        <div style="margin-top: 40px"></div>
        {#        {% for i in a %}#}
        {#            {% for j in i %}#}
        {#                <h5>练习题：{{ j.exercises.exercises }}</h5>#}
        {#                <h5>时间：{{ j.myTime }}</h5>#}
        {#                <h5>成绩：{{ j.grade }}</h5>#}
        {#                <h5> id：{{ j.id }}</h5>#}
        {#                <h5> id：{{ i }}</h5>#}
        {#                <hr>#}
        {#            {% endfor %}#}


        {#        {% endfor %}#}

        {% for i in exercise %}



            <div class="alert alert-primary text-black" role="alert">
                <div class="row">
                    <div class="col-md-9">
                        <h5>{{ i.exercises }}
                            {% if i.exercises2_set.get != '' %}
                                <span class="badge bg-success " style="font-size: 10px">已完成</span>
                            {% else %}
                                <span class="badge bg-warning text-dark" style="font-size: 10px">待完成</span>
                            {% endif %}
                        </h5>

                        <p>
                            创建时间：{{ i.myTime }}
                        </p>
                    </div>
                    <div class="col-3 text-center">

                        {% if i.exercises2_set.get != '' %}
                            <h3 style="color:#de2323;font-family: '华文行楷'">成绩：{{ i.exercises2_set.get }} %</h3>
                            <a href="{% url 'students_showGrade' i.course.id  i.id %}" class="btn btn-sm btn-primary">查看作业</a>
                        {% else %}
                            <p></p>
                            <a href="{% url 'students_exercises_start' i.course.id  i.id %}"
                               class="btn btn-primary w-50 ">开始做</a>
                        {% endif %}


                    </div>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock %}

students/templates/studentes/prompt.html
{% extends 'studentes/base.html' %}

{% block students_index %}
    <div class="col-md-10 offset-1" style="margin-top: 30px">
        <h3>&emsp;&emsp;提示：</h3>
        <hr>
        <div class="alert alert-warning  " style="font-size: 18px;" role="alert">
            {{ msg }}
        </div>
    </div>






{% endblock %}

students/templates/studentes/showGrade.html
{% extends 'studentes/base.html' %}
{% block students_index %}
    <div class="container">

            {% csrf_token %}
            <div class="col-8 offset-2" style="border: 1px solid #4f4848;border-radius: 15px;
        background-color: rgba(169,162,162,0.05);margin-top: 30px;margin-bottom: 40px;">
                <div style="margin: 30px 30px 30px 30px ">
                    <div class="text-center">
                        <h4 style="">{{ exercise.exercises }}</h4>
                        <h3 style="color:#de2323;font-family: '华文行楷'" class="text-end">
                            成绩：{{ exercise.exercises2_set.get }} %</h3>
                        <p>时间：{{ exercise.exercises2_set.get.myTime }}</p>
                    </div>
                    {#        for 语句#}

                    {% for i in answer %}
                        <h6 class="form-label"><span class="badge rounded-pill bg-success">{{ forloop.counter }}</span>&emsp;{{ i.title }}
                            <div class="text-end">
                                {% if i.correctAnswer == i.answer2_set.get.stuAnswer %}
                                    <span class="badge bg-success">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-check-lg" viewBox="0 0 16 16">
  <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
</svg>
                                </span>
                                {% else %}
                                    <span class="badge bg-danger">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16"
                                         height="16" fill="currentColor" class="bi bi-x-lg"
                                         viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M13.854 2.146a.5.5 0 0 1 0 .708l-11 11a.5.5 0 0 1-.708-.708l11-11a.5.5 0 0 1 .708 0Z"/>
  <path fill-rule="evenodd" d="M2.146 2.146a.5.5 0 0 0 0 .708l11 11a.5.5 0 0 0 .708-.708l-11-11a.5.5 0 0 0-.708 0Z"/>
</svg>
                                    </span>
                                {% endif %}


                            </div>
                        </h6>

                        <div style="margin-left: 30px;font-size: small">
                            <div class="form-check">
                                <input required="required" disabled class="form-check-input" type="radio"
                                       name="{{ i.id }}"
                                       id="flexRadioDefault-a-{{ i.id }}" value="1">
                                <label class="form-check-label w-100" for="flexRadioDefault-a-{{ i.id }}">
                                    A.{{ i.answerA }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input required="required" disabled class="form-check-input" type="radio"
                                       name="{{ i.id }}"
                                       id="flexRadioDefault-b-{{ i.id }}" value="2">
                                <label class="form-check-label w-100" for="flexRadioDefault-b-{{ i.id }}">
                                    B.{{ i.answerB }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input required="required" disabled class="form-check-input" type="radio"
                                       name="{{ i.id }}"
                                       id="flexRadioDefault-c-{{ i.id }}" value="3">
                                <label class="form-check-label w-100" for="flexRadioDefault-c-{{ i.id }}">
                                    C.{{ i.answerC }}
                                </label>
                            </div>
                            <div class="form-check">
                                <input required="required" disabled class="form-check-input" type="radio"
                                       name="{{ i.id }}"
                                       id="flexRadioDefault-d-{{ i.id }}" value="4">
                                <label class="form-check-label w-100" for="flexRadioDefault-d-{{ i.id }}">
                                    D.{{ i.answerD }}
                                </label>
                            </div>
                            <br>
                            <div class="mb-3">
                                <h6 style="color: #af4b4b">你的答案：

                                    {% if i.answer2_set.get.stuAnswer == 1 %}
                                        A
                                    {% elif i.answer2_set.get.stuAnswer == 2 %}
                                        B
                                    {% elif i.answer2_set.get.stuAnswer == 3 %}
                                        C
                                    {% elif i.answer2_set.get.stuAnswer == 4 %}
                                        D
                                    {% endif %}
                                </h6>
                                <h6 style="color: #af4b4b">正确答案：
                                    {% if i.correctAnswer == 1 %}
                                        A
                                    {% elif i.correctAnswer == 2 %}
                                        B
                                    {% elif i.correctAnswer == 3 %}
                                        C
                                    {% elif i.correctAnswer == 4 %}
                                        D
                                    {% endif %}
                                </h6>

                            </div>

                            <br>

                        </div>

                    {% endfor %}

                </div>
            </div>

    </div>


{% endblock %}