login/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('user_edit/', views.user_edit, name='user_edit'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name="register"),
    path('teachers_register/', views.teachers_register, name="teachers_register"),
    path('logout/', views.logout, name='logout'),
    path('pswd_edit/', views.pswd_edit, name='pswd_edit'),

]

teachers/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="teachers_index"),  # 教师端首页
    path('cource_add/', views.cource_add, name="cource_add"),  #
    path('cource_edit/<int:id>', views.cource_edit, name="cource_edit"),  #
    path('cource_del/<int:id>', views.cource_del, name="cource_del"),  # 课程删除
    path('cource_chapter_add/<int:id>', views.cource_chapter_add, name="cource_chapter_add"),  # 添加章
    path('cource_chapter_edit/<int:id>/<int:chapter_id>', views.cource_chapter_edit, name="cource_chapter_edit"),  # 编辑章
    path('cource_chapter_del/<int:id>/<int:chapter_id>', views.cource_chapter_del, name="cource_chapter_del"),  # 删除章
    path('cource_section_add/<int:id>/<int:chapter_id>', views.cource_section_add, name="cource_section_add"),  # 添加节
    path('cource_section_edit/<int:id>/<int:chapter_id>/<int:section_id>', views.cource_section_edit,
         name="cource_section_edit"),  # 添加节
    path('cource_section_del/<int:id>/<int:chapter_id>/<int:section_id>', views.cource_section_del,
         name="cource_section_del"),  # 添加节
    path('cource_section_msg/<int:id>/<int:chapter_id>/<int:section_id>', views.cource_section_msg,
         name="cource_section_msg"),  # 课程评论留言
    # 练习题
    path('exercises/<int:id>', views.exercises, name="exercises"),  # 练习题
    path('exercises_add/<int:id>', views.exercises_add, name="exercises_add"),  # 练习题添加
    path('exercises_del/<int:id>/<int:exercises_id>', views.exercises_del, name="exercises_del"),  # 练习题删除
    path('exercises_edit/<int:exercise_id>', views.exercises_edit, name="exercises_edit"),  # 练习题编辑
    path('ansewer_add/<int:exercise_id>', views.ansewer_add, name="ansewer_add"),  # 添加题
    path('ansewer_edit/<int:exercise_id>/<ansewer_id>', views.ansewer_edit, name="ansewer_edit"),  # 修改题
    path('ansewer_del/<int:exercise_id>/<ansewer_id>', views.ansewer_del, name="ansewer_del"),  # 修改题


]

zaixianxuexixitong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('login.urls')),
                  path('teachers/', include('teachers.urls')),
                  path('students/', include('students.urls')),
                  path('myadmin/', include('myadmin.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  ## 没有这一句无法显示上传的图片

login/models.py
import datetime

from django.db import models


# students
class User(models.Model):
    name = models.CharField(verbose_name="用户名", max_length=32, default='')  #
    teacher_id = models.CharField(verbose_name="id", max_length=32, default='')  #
    teacher_name = models.CharField(verbose_name="姓名", max_length=32, default='')  #
    type = models.IntegerField(verbose_name="类型", default=1)  # 1普通用户|3教工号|4审核状态|5拒绝|6管理员|9禁用
    password = models.CharField(verbose_name="密码", max_length=32, default='')  # 管理员密码
    Class = models.CharField(verbose_name="班级", max_length=32, default='')
    academy = models.CharField(verbose_name="学院", max_length=32, default='')
    email = models.EmailField(verbose_name="邮箱", default='')
    phone = models.CharField(verbose_name="手机号", max_length=18, default='')
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    photo = models.ImageField(verbose_name="头像", upload_to='static/students/photo/', default='')
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'User'
        # 后台管理名
        verbose_name_plural = '用户列表'


# 课程名
class Course(models.Model):
    name = models.CharField(verbose_name="课程名", max_length=32, default='')  # 课程名
    type = models.IntegerField(verbose_name="课程类型", default=0)
    # 1.哲学|2.经济学|3.法学|4.教育学|5.文学
    user = models.ForeignKey(verbose_name="用户名", to="User", on_delete=models.CASCADE, default='')  # 创建用户名
    photo = models.FileField(verbose_name="资源存放名字", upload_to='Course/', default='')  # 课程图片
    introduction = models.TextField(verbose_name="课程简介")  # 课程简介
    audit = models.IntegerField(verbose_name="审核", default=1)  # 审核状态 1审核中|   2已审核|   3审核失败
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Course'
        # 后台管理名
        verbose_name_plural = '课程'


# 章
class Chapter(models.Model):
    name = models.ForeignKey(to="Course", on_delete=models.CASCADE, default='', null=True)  # 课程名
    chapter = models.CharField(verbose_name="章", max_length=210, default="")  # 章
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Chapter'
        # 后台管理名
        verbose_name_plural = '章'


# pdf,mp4资源
class Media(models.Model):
    type = models.IntegerField(verbose_name="类型", default=0)  # 1.pdf| 2.mp4   |3.word | 4.powerPoint
    media = models.FileField(verbose_name="资源存放地址", upload_to='static/Media/', default='')
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.media

    class Meta:
        # 数据库列表名
        db_table = 'Media'
        # 后台管理名
        verbose_name_plural = '资源存放地址'


# 节
class Section(models.Model):
    name = models.ForeignKey(to="Chapter", on_delete=models.CASCADE, default='')  # 章
    section = models.CharField(verbose_name="节", max_length=210, default="")
    media = models.ForeignKey(Media, on_delete=models.CASCADE)

    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Section'
        # 后台管理名
        verbose_name_plural = '节'


# message留言
class Message(models.Model):
    name = models.ForeignKey(to="Section", on_delete=models.CASCADE, default='')  # 节
    user = models.ForeignKey(to="User", on_delete=models.CASCADE, default='')
    message = models.CharField(verbose_name="留言", max_length=210, default='')  # 留言
    myTime = models.DateTimeField(verbose_name="参加时间", auto_now_add=True)

    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.name

    class Meta:
        # 数据库列表名
        db_table = 'Message'
        # 后台管理名
        verbose_name_plural = '留言'


# 选课
class Course2(models.Model):
    students = models.ForeignKey(to="User", on_delete=models.CASCADE, default='')  # 用户名
    course = models.ForeignKey(to="Course", on_delete=models.CASCADE, default='')  # 课程名
    myTime = models.DateTimeField(verbose_name="参加时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.course

    class Meta:
        # 数据库列表名
        db_table = 'course2'
        # 后台管理名
        verbose_name_plural = '选课'


# 练习、习题
class Exercises(models.Model):
    exercises = models.CharField(verbose_name="练习题", max_length=210, default='')
    course = models.ForeignKey(verbose_name='课程', to="Course", on_delete=models.CASCADE, default='')
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.exercises

    class Meta:
        # 数据库列表名
        db_table = 'Exercises'
        # 后台管理名
        verbose_name_plural = '习题'


class Exercises2(models.Model):
    user = models.ForeignKey(verbose_name="用户", to="User", on_delete=models.CASCADE, default='')
    exercises = models.ForeignKey(verbose_name="联系题名", to="Exercises", on_delete=models.CASCADE, default='')
    course2 = models.ForeignKey(verbose_name='课程', to="Course2", on_delete=models.CASCADE, default='')
    grade = models.DecimalField(verbose_name="成绩", max_digits=5, decimal_places=2)
    myTime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        grade = str(self.grade)
        return grade

    class Meta:
        # 数据库列表名
        db_table = 'Exercises2'
        # 后台管理名
        verbose_name_plural = '习题成绩'


# 选择题
class Answer(models.Model):
    exercises = models.ForeignKey(to="Exercises", on_delete=models.CASCADE, default='')
    title = models.TextField(verbose_name="问题", max_length=210, default='')
    answerA = models.CharField(verbose_name="答案A", max_length=110, default='')
    answerB = models.CharField(verbose_name="答案B", max_length=110, default='')
    answerC = models.CharField(verbose_name="答案C", max_length=110, default='')
    answerD = models.CharField(verbose_name="答案D", max_length=110, default='')
    correctAnswer = models.IntegerField(verbose_name="正确答案", default=0)  # A B C D ___ 1 2 3 4
    number = models.IntegerField(verbose_name="分值", default=2)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        return self.title

    class Meta:
        # 数据库列表名
        db_table = 'Answer'
        # 后台管理名
        verbose_name_plural = '选择题'


class Answer2(models.Model):
    user = models.ForeignKey(verbose_name="学生", to="User", on_delete=models.CASCADE, default="")
    exercises = models.ForeignKey(verbose_name="练习题", to="Exercises", on_delete=models.CASCADE, default="")
    answer = models.ForeignKey(verbose_name="问题", to="Answer", on_delete=models.CASCADE, default='')
    stuAnswer = models.IntegerField(verbose_name="学生答案", default=0)
    is_active = models.BooleanField('是否活跃', default=True)

    def __str__(self):
        answer = str(self.stuAnswer)
        return answer

    class Meta:
        # 数据库列表名
        db_table = 'Answer2'
        # 后台管理名
        verbose_name_plural = '学生答案'


class Teachers(models.Model):
    nickName = models.CharField(verbose_name="用户名", max_length=110, default='')
    name = models.CharField(verbose_name="姓名", max_length=110, default='')
    type = models.IntegerField(verbose_name="类型", default=1)  # 1普通用户|6管理员|9禁用
    password = models.CharField(verbose_name="密码", max_length=32, default='')  # 管理员密码
    email = models.EmailField(verbose_name="邮箱", default='')
    phone = models.CharField(verbose_name="手机号", max_length=11, default='')
    photo = models.ImageField(verbose_name="头像", upload_to='teachers/photo/', default='')
    myTime = models.DateTimeField(verbose_name="参加时间", auto_now_add=True)
    is_active = models.BooleanField('是否活跃', default=True)


class MyTime(models.Model):
    myTime = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=110, default='')

teachers/models.py
from django.db import models

# Create your models here.

teachers/templates/teachers/base.html
<!doctype html>
<html lang="zh-CN">
<head>
    {% load static %}
    <!-- 必须的 meta 标签 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap 的 CSS 文件 -->
    <link href="{% static  'bootsrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootsrap/js/bootstrap.bundle.min.js' %}"></script>

    <title>学生首页</title>
    <link rel="icon" href="{% static 'img/tubiao.jpg' %}" type="image/x-icon">


    <style type="text/css">

    </style>
    {% load static %}
</head>

{% load static %}
<body  background="{% static 'img/background.jpg' %}" style=" background-repeat:no-repeat ;background-size:100% 100%;
background-attachment: fixed;">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">在线学习系统</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'teachers_index' %}">我的课程</a>
                </li>


            </ul>
            <ul class="navbar-nav  d-flex dropdown" style="--bs-scroll-height: 100px;margin-right: 30px">


                <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    欢迎您:{{ request.session.name }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                    {% if request.session.type == 3 %}
                        <li><a class="dropdown-item" href="{% url 'students_index' %}">切换学生端</a></li>
                    {% elif request.session.type == 6 %}
                        <li><a class="dropdown-item" href="{% url 'myadmin_index' %}">切换后台管理端</a></li>
                    {% elif  request.session.type == 1 %}
                        <li><a class="dropdown-item" href="{% url 'teachers_register' %}">审核教师</a></li>
                    {% elif  request.session.type == 4 %}
                        <li><a class="dropdown-item" href="{% url 'teachers_register' %}">提交教师审核</a></li>
                    {% endif %}

                    <li><a class="dropdown-item" href="#">编辑资料</a></li>
                    <li><a class="dropdown-item" href="#">修改密码</a></li>
                    <li><a class="dropdown-item" href="/logout/">退出登录</a></li>

                </ul>
            </ul>
            {#      <form class="d-flex">#}
            {#        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
            {#        <button class="btn btn-outline-success" type="submit">Search</button>#}
            {#      </form>#}
        </div>
    </div>
</nav>

<div class="col" style="background-color: white;padding: 30px 30px 30px 30px;margin: 20px 20px 20px 20px;border-radius: 20px;">
{% block teachers_index %}

{% endblock %}
</div>
</body>


</html>

teachers/templates/teachers/cource_add.html
{% extends 'teachers/base.html' %}
{% block teachers_index %}
    {% load static %}

    <div class="col-md-6 offset-3" style="border: 1px solid black;border-radius: 15px;margin-top: 30px">
        <div style="margin: 30px 30px 30px 30px">
            <h3 style="margin-top: 30px">&emsp;&emsp;添加课程</h3>
            <hr>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row mb-3">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">课程名</label>
                    <div class="col-sm-10">
                        <input name="name" required type="text" class="form-control" id="inputEmail3">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">图片</label>
                    <div class="col-sm-10">
                        <input required type="file" class="form-control" id="inputPassword3" name="photo">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">课程简介</label>
                    <div class="col-sm-10">
                        <textarea name="introduction" required class="form-control" id="exampleFormControlTextarea1"
                                  rows="3"></textarea>
                    </div>
                </div>


                <fieldset class="row mb-3">
                    <legend class="col-form-label col-sm-2 pt-0">课程类型</legend>
                    <div class="col-sm-10">
                        <select name="type" required class="form-select" aria-label="Default select example">
                            <option selected>选择课程类型</option>
                            <option value="1">加工学</option>

                        </select>

                    </div>
                </fieldset>

                <br>
                <button type="submit" class="btn btn-primary offset-9 w-25">保存</button>
            </form>
        </div>
    </div>
{% endblock %}

teachers/templates/teachers/index.html
{% extends 'teachers/base.html' %}
{% block teachers_index %}
    {% load static %}
    <div class="">
        <h3 style="margin-top: 30px">&emsp;&emsp;我的课程</h3>

        <table class="table table-striped table-hover text-center  "
               style="vertical-align: middle;text-align: center;">
            <thead>
            <tr>
                <th scope="col">序号</th>
                <th scope="col">封面图片</th>
                <th scope="col">课程名</th>
                <th scope="col">课程类</th>
                <th scope="col">创建时间</th>
                <th scope="col">审核状态</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for i in cource %}



                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img src="/static/media/{{ i.photo }}" height="60px" alt=""></td>
                    <td>{{ i.name }}</td>

                    <td>{% if i.type == 1 %}
                        工学

                    {% endif %} </td>
                    <td>
                        {{ i.myTime | date }}
                    </td>
                    {% if i.audit == 1 %}
                        <td style="color: #e3c00f">
                            审核中
                        </td>
                    {% elif i.audit == 2 %}
                        <td style="color: rgba(16,124,34,0.87)">
                            审核成功
                        </td>
                    {% elif i.audit == 3 %}
                        <td style="color: rgba(239,9,43,0.87)">
                            审核失败！
                        </td>
                    {% endif %}


                    <td>
                        <a href="{% url 'cource_edit' i.id %}"
                           class="btn btn-primary btn-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-pen" viewBox="0 0 16 16">
                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                            </svg>
                            编辑</a>
                        <a href="{% url 'exercises' i.id %}"
                           class="btn btn-success  btn-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-clipboard-plus" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
                                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                            </svg>
                            练习题</a>
                        <a onclick="if(confirm('确定删除吗？')==false)return false;location.href=('{% url 'cource_del' i.id %}')"
                           class="btn btn-danger  btn-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                 class="bi bi-x" viewBox="0 0 16 16">
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                            删除
                        </a>

                    </td>
                </tr>
            {% empty %}
                <div class="text-center " style="height: 150px;">
                    <h4 style="margin-top: 50px;color: #1c51a1">请添加练课程！</h4>
                </div>
            {% endfor %}


            </tbody>
        </table>

        <hr>
        <a href="{% url 'cource_add' %}" type="button" class="btn btn-primary offset-11">添加新课程</a>

    </div>
{% endblock %}

teachers/templates/teachers/prompt.html
{% extends 'teachers/base.html' %}

{% block teachers_index %}
    <div class="container">
    <div class="col-md-11" style="margin-top: 30px">
        <h3>&emsp;&emsp;提示：</h3>
        <hr>
        <div class="alert alert-warning  " role="alert">
            {{ msg }}
        </div>
    </div>

    </div>




{% endblock %}

teachers/templates/teachers/teachers_exercises.html
{% extends 'teachers/base.html' %}
{% block teachers_index %}
    {% load static %}
    <div class="container">
        <br>
        <h3>&emsp;{{ course.name }}</h3>
        <hr>
        {% for i in exercises %}



            <div class="alert alert-primary text-black" role="alert">

                <div class="row">
                    <div class="col-md-9">
                        <h5>{{ i.exercises }}</h5>
                        <p>

                            题目数量：{{ i.answer_set.count }} ，总分：{{ i.answer_set.count }}，创建时间：{{ i.myTime }}
                        </p>
                    </div>
                    <div class="col-3 text-center">
                        <p></p>
                        <a href="{% url 'exercises_edit'  i.id %}" class="btn btn-primary w-25 ">编辑</a>

                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger btn w-25" data-bs-toggle="modal"
                                data-bs-target="#staticBackdrop_my{{ i.id }}">
                            删除
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="staticBackdrop_my{{ i.id }}" data-bs-backdrop="static"
                             data-bs-keyboard="false"
                             tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">确定删除吗？</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body text-start">
                                        确定删除“{{ i.exercises }}”吗？
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消
                                        </button>
                                        <a href="{% url 'exercises_del' course.id i.id %}" type="button"
                                           class="btn btn-danger">确定删除</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        {% empty %}
            <div class="text-center " style="height: 150px;">
                <h4 style="margin-top: 50px;color: #1c51a1">请添加练习题！</h4>
            </div>
        {% endfor %}
        <br>

        <!-- Button trigger modal -->
        <div class="text-end">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop_add">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                     class="bi bi-plus-lg"
                     viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
                </svg>
                &nbsp;添加练习题
            </button>

            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop_add" data-bs-backdrop="static" data-bs-keyboard="false"
                 tabindex="-1"
                 aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form action="{% url 'exercises_add' course.id %}" method="get">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">&emsp;添加练习题 </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="text-start">
                                    <div class="mb-3">
                                        <label class="form-label">练习题名</label>
                                        <input name="name" type="text" class="form-control">

                                    </div>

                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                                <button type="submit" class="btn btn-primary">确定</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>





{% endblock %}